name: Deploy - Checkout Web SDK

on:
  workflow_call:
    inputs:
      environment:
        type: string
      branch:
        type: string
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Deployment Environment
        options:
          - red
          - coffee
          - fail
          - how
          - io
          - maison
          - ninja
          - rocks
          - wtf

permissions:
  id-token: write
  contents: read

jobs:
  Deploy:
    name: Initialize
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Initialize outputs
        id: init
        env:
          ENVIRONMENT: ${{ inputs.environment }}
        run: |
          case $ENVIRONMENT in
            how|rip|rocks|wtf)
              echo "region=us-west-2" >> $GITHUB_OUTPUT
              ;;
            *)
              echo "region=us-east-1" >> $GITHUB_OUTPUT
              ;;
          esac

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ASSUME_ROLE }}
          role-session-name: rch-github-runner
          aws-region: ${{ steps.init.outputs.region }}

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          npm install

      - name: Audit packages
        run: |
          npm audit --audit-level=high --production

      - name: Build
        run: |
          webpack

      - name: Deploy to ${{ inputs.environment }}
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          REGION: ${{ steps.init.outputs.region }}
        run: |
          aws s3 sync dist s3://rch-cf-assets-${ENVIRONMENT}-${REGION}/sdk/checkout-web --no-progress
